# Generated by Django 2.2.4 on 2019-08-18 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='time',
            field=models.FileField(upload_to='images/'),
        ),
    ]
