# Generated by Django 2.2.4 on 2019-08-18 20:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('volunteering', '0002_auto_20190818_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteering',
            name='extra',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
