# Generated by Django 2.2.4 on 2019-08-19 22:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_num',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
