# Generated by Django 2.2.4 on 2019-08-10 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Eduaction',
            new_name='Education',
        ),
    ]
