# Generated by Django 2.2.4 on 2019-08-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_auto_20190810_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='beginning',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='end',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
